services:
  local_page:
    image: nginx:alpine
    container_name: local-page-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./app:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
