server {
    listen 80;
    listen [::]:80;
    server_name localhost links.lan;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Zapobiega błędom w logach o brakujący favicon
    location = /favicon.ico { 
        log_not_found off; 
        access_log off; 
    }
}
