services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Warsaw

  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    volumes:
      - ./matter_data:/data
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Warsaw
    command:
      - "--primary-interface"
      - "wlo1"
      - "--storage-path"
      - "/data"
      - "--paa-root-cert-dir"
      - "/data/credentials"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: unless-stopped

    networks:
      - homelab

    ports:
      - "1883:1883"

    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped

    networks:
      - homelab

    ports:
      - "8099:8099"

    volumes:
      - ./zigbee2mqtt/data:/app/data

    environment:
      - TZ=Europe/Warsaw

networks:
  homelab:
    external: true
