- id: '1763460687683'
  alias: Elektryzer - AutoOff
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 00:30:00
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.switch_zb_10
  mode: single
- id: '1763460776788'
  alias: Elektryzer - AutoOn
  triggers:
  - event: sunset
    offset: -00:30:00
    trigger: sun
  actions:
  - repeat:
      count: 10
      sequence:
      - target:
          entity_id: switch.switch_zb_10
        action: switch.turn_on
      - delay: 00:00:30
      - condition: state
        entity_id: switch.switch_zb_10
        state: 'off'
  mode: single
- id: '1763472760185'
  alias: Lamps Front - AutoOff
  description: ''
  triggers:
  - event: sunrise
    trigger: sun
  conditions: []
  actions:
  - target:
      entity_id: switch.lampy_dom_front
    action: switch.turn_off
  mode: single
- id: '1763473145807'
  alias: Lamps Front - AutoOn
  description: ''
  triggers:
  - event: sunset
    trigger: sun
  conditions: []
  actions:
  - target:
      entity_id: switch.lampy_dom_front
    action: switch.turn_on
  mode: single
- id: '1763573075931'
  alias: Ladowanie Galaxy automatyczne
  description: Włącza i wyłącza ładowanie telefonu Galaxy w zależności od poziomu
    baterii
  triggers:
  - entity_id:
    - sensor.galaxy_battery_level
    below: 30
    trigger: numeric_state
  - entity_id:
    - sensor.galaxy_battery_level
    above: 75
    trigger: numeric_state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.galaxy_battery_level
        below: 30
      sequence:
      - action: switch.turn_on
        data: {}
        target:
          entity_id: switch.switch_galaxy
    - conditions:
      - condition: numeric_state
        entity_id: sensor.galaxy_battery_level
        above: 75
      sequence:
      - action: switch.turn_off
        data: {}
        target:
          entity_id: switch.switch_galaxy
  mode: single
- id: rekuperator_sterowanie_final
  alias: Rekuperator – smart v3 (bez błędów)
  triggers:
  - minutes: /5
    trigger: time_pattern
  conditions:
  - condition: template
    value_template: '{% set last = state_attr(''automation.rekuperator_smart_v3'',
      ''last_triggered'') %} {{ last is none or (now() - last).total_seconds() > 600
      }}

      '
  actions:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.th_11_temperature
        below: 5
      - condition: template
        value_template: '{{ t_in < 19 }}'
      sequence:
      - target:
          entity_id: switch.switch_rekuperator
        action: switch.turn_off
    - conditions:
      - condition: numeric_state
        entity_id: sensor.th_11_temperature
        below: 5
      sequence:
      - target:
          entity_id: switch.switch_rekuperator
        action: switch.turn_on
    - conditions:
      - condition: numeric_state
        entity_id: sensor.th_11_temperature
        above: 10
      - condition: template
        value_template: '{{ t_out < t_in }}'
      sequence:
      - target:
          entity_id: switch.switch_rekuperator
        action: switch.turn_on
    - conditions:
      - condition: numeric_state
        entity_id: sensor.th_05_humidity
        above: 60
      sequence:
      - target:
          entity_id: switch.switch_rekuperator
        action: switch.turn_on
    - conditions:
      - condition: numeric_state
        entity_id: sensor.th_05_temperature
        above: 24
      sequence:
      - target:
          entity_id: switch.switch_rekuperator
        action: switch.turn_on
    default:
    - target:
        entity_id: switch.switch_rekuperator
      action: switch.turn_on
    - delay: 00:10:00
    - target:
        entity_id: switch.switch_rekuperator
      action: switch.turn_off
  variables:
    t_in: '{{ states(''sensor.th_05_temperature'') | float }}'
    t_out: '{{ states(''sensor.th_11_temperature'') | float }}'
    hum: '{{ states(''sensor.th_05_humidity'') | float }}'
  mode: restart
- id: swiatla_wlacz_45_po_zachodzie
  alias: Światła świąteczne – włącz 45 min po zachodzie
  triggers:
  - event: sunset
    offset: 00:45:00
    trigger: sun
  actions:
  - action: switch.turn_on
    data: {}
    target:
      entity_id: switch.switch_swiatla
  mode: single
- id: swiatla_wylacz_2330
  alias: Światła świąteczne – wyłącz o 23:30
  triggers:
  - at: '23:30:00'
    trigger: time
  actions:
  - action: switch.turn_off
    data: {}
    target:
      entity_id: switch.switch_swiatla
  mode: single
- id: swiatla_wlacz_0500
  alias: Światła świąteczne – włącz o 05:00
  triggers:
  - at: 05:00:00
    trigger: time
  actions:
  - action: switch.turn_on
    data: {}
    target:
      entity_id: switch.switch_swiatla
  mode: single
- id: swiatla_wylacz_0600
  alias: Światła świąteczne – wyłącz o 06:00
  triggers:
  - at: 06:00:00
    trigger: time
  actions:
  - action: switch.turn_off
    data: {}
    target:
      entity_id: switch.switch_swiatla
  mode: single
- id: '1771069583392'
  alias: Alert notify - elektryzer
  description: Alert jeśli elektryzer nie jest włączony lub nie odpowiada
  triggers:
  - event: sunset
    offset: -00:10:00
    trigger: sun
  conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: sswitch.switch_zb_10
      state: 'off'
    - condition: state
      entity_id: switch.switch_zb_10
      state: unavailable
    - condition: state
      entity_id: switch.switch_zb_10
      state: unknown
  actions:
  - data:
      title: ⚠️ HA – Elektryzer
      message: 'Elektryzer jest OFF lub nie odpowiada (20 minut przed zachodem słońca).

        '
      data:
        importance: high
        priority: high
        ttl: 0
    action: notify.mobile_app_pococ6
  mode: single
- id: '1771071726782'
  alias: Alert notify - Lamps Front
  description: Alert jeśli oświetlenie nie jest włączone lub nie odpowiada
  triggers:
  - event: sunset
    offset: 00:10:00
    trigger: sun
  conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: switch.lampy_dom_front
      state: 'off'
    - condition: state
      entity_id: switch.lampy_dom_front
      state: unavailable
    - condition: state
      entity_id: switch.lampy_dom_front
      state: unknown
  actions:
  - data:
      title: ⚠️ HA – Check Lamps Front
      message: 'Sprawdź oświetlenie na froncie domu.

        '
      data:
        importance: high
        priority: high
        ttl: 0
    action: notify.mobile_app_pococ6
  mode: single
- id: '1771074212224'
  alias: Ładowanie Oppo automatyczne
  description: Włącza i wyłącza ładowanie telefonu Oppo w zależności od poziomu baterii
  triggers:
  - entity_id:
    - sensor.oppo_battery_level
    below: 30
    trigger: numeric_state
  - entity_id:
    - sensor.oppo_battery_level
    above: 75
    trigger: numeric_state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.oppo_battery_level
        below: 30
      sequence:
      - action: switch.turn_on
        data: {}
        target:
          entity_id: switch.switch_swiatla
    - conditions:
      - condition: numeric_state
        entity_id: sensor.oppo_battery_level
        above: 75
      sequence:
      - action: switch.turn_off
        data: {}
        target:
          entity_id: switch.switch_swiatla
  mode: single
- id: '1771119082882'
  alias: Oppo wybudz po ruchu
  description: ''
  triggers:
  - entity_id: binary_sensor.md_01_occupancy
    to: 'on'
    trigger: state
  actions:
  - action: shell_command.oppo_screen_on
  mode: restart
- id: '1771177420364'
  alias: Oppo ADB keep connection
  description: ''
  triggers:
  - trigger: time_pattern
    minutes: /5
  conditions: []
  actions:
  - action: shell_command.oppo_adb_connect
    data: {}
  mode: restart
- id: '1771269738328'
  alias: Kotlownia - Monitor gryzoni
  triggers:
  - entity_id: binary_sensor.md_01_occupancy
    to: 'on'
    trigger: state
  conditions:
  - condition: numeric_state
    entity_id: sensor.md_01_illuminance
    below: 10
  - condition: template
    value_template: "{{ (as_timestamp(now()) -\n   as_timestamp(state_attr(this.entity_id,'last_triggered')
      | default(0))) > 30 }}\n"
  actions:
  - target:
      entity_id: counter.kotlownia_gryzonie
    action: counter.increment
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: counter.kotlownia_gryzonie
        above: 9
      sequence:
      - data:
          title: "\U0001F42D Mozliwa aktywnosc gryzoni"
          message: 'W kotlowni wykryto {{ states(''counter.kotlownia_gryzonie'') }}
            zdarzen ruchu w ciemnosci.

            '
        action: notify.mobile_app_pococ6
      - target:
          entity_id: counter.kotlownia_gryzonie
        action: counter.reset
  - delay: 01:00:00
  - target:
      entity_id: counter.kotlownia_gryzonie
    action: counter.reset
  mode: restart
- id: '1776278737381'
  alias: Lamp west - AutoOff
  description: Lamp west - AutoOff
  triggers:
  - event: sunrise
    offset: -00:45:00
    trigger: sun
  conditions: []
  actions:
  - target:
      entity_id: switch.switch_lamp_west
    action: switch.turn_off
  mode: single
- id: '1776278794623'
  alias: Lamp west - AutoOn
  description: Lamp west - AutoOn
  triggers:
  - event: sunset
    offset: 00:45:00
    trigger: sun
  conditions: []
  actions:
  - target:
      entity_id: switch.switch_lamp_west
    action: switch.turn_on
  mode: single
- id: '1776978328753'
  alias: Poco C6 - stop ładowania przy 85%
  description: ''
  triggers:
  - entity_id: sensor.pococ6_battery_level
    above: 85
    trigger: numeric_state
  conditions:
  - condition: state
    entity_id: person.szymon
    state: home
  - condition: state
    entity_id: sensor.pococ6_battery_state
    state: charging
  actions:
  - target:
      entity_id: switch.switch_wf_10
    action: switch.turn_off
  mode: single
- id: '1776978444032'
  alias: Poco C6 - start ładowania gdy podłączony i niski poziom
  description: ''
  triggers:
  - entity_id: sensor.pococ6_battery_state
    to: charging
    trigger: state
  conditions:
  - condition: state
    entity_id: person.szymon
    state: home
  - condition: numeric_state
    entity_id: sensor.pococ6_battery_level
    below: 75
  actions:
  - target:
      entity_id: switch.switch_wf_10
    action: switch.turn_on
  mode: single
- id: '1779821616225'
  alias: 'Ogród: Automatyczne podlewanie trawnika'
  description: Uruchamia podlewanie codziennie o 06:00 od maja do września. Przygotowane
    pod czujnik wilgotności.
  triggers:
  - at: 06:00:00
    trigger: time
  conditions:
  - condition: template
    value_template: '{{ now().month in [5, 6, 7, 8, 9] }}'
  actions:
  - target:
      entity_id: switch.aquavalve_01_lawn
    action: switch.turn_on
  - delay: 00:08:00
  - target:
      entity_id: switch.aquavalve_01_lawn
    action: switch.turn_off
  mode: single
