---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- resources:
    backend: docker
    containers:
      - reverse-proxy

- search:
    provider: duckduckgo
    target: _blank
